P_POSITIVE_GIVEN_VAMPIRE = 0.95
P_POSITIVE_GIVEN_MORTAL = 0.01
P_VAMPIRE = 0.001
P_POSITIVE = P_POSITIVE_GIVEN_VAMPIRE * P_VAMPIRE + P_POSITIVE_GIVEN_MORTAL * (
    1 - P_VAMPIRE
)
P_VAMPIRE_GIVEN_POSITIVE = P_POSITIVE_GIVEN_VAMPIRE * P_VAMPIRE / P_POSITIVE
print(
    f"The probability of vampirism, given a positive test result is {round(P_VAMPIRE_GIVEN_POSITIVE, 3)}."
)
